/*
 * Apache Ambari - Management Pack Store Provider APIs
 * Management pack store provider APIs for Apache Ambari  [Learn about Apache Ambari](https://ambari.apache.org/) 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ambari.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AssetCollection;
import io.swagger.client.model.AssetWrapper;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AssetApi
 */
@Ignore
public class AssetApiTest {

    private final AssetApi api = new AssetApi();

    
    /**
     * Get asset
     *
     * Returns an asset by id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAssetByIdTest() throws ApiException {
        Long assetId = null;
        AssetWrapper response = api.getAssetById(assetId);

        // TODO: test validations
    }
    
    /**
     * List assets 
     *
     * Returns a list of assets
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAssetsTest() throws ApiException {
        AssetCollection response = api.getAssets();

        // TODO: test validations
    }
    
}
