/*
 * Swagger Server
 * Management pack store provider APIs for Apache Ambari  [Learn about Apache Ambari](https://ambari.apache.org/) 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ambari.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AssetWrapper;
import java.util.ArrayList;
import java.util.List;

/**
 * AssetCollection
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T02:01:49.620Z")
public class AssetCollection {
  @SerializedName("href")
  private String href = null;

  @SerializedName("items")
  private List<AssetWrapper> items = new ArrayList<AssetWrapper>();

  public AssetCollection href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public AssetCollection items(List<AssetWrapper> items) {
    this.items = items;
    return this;
  }

  public AssetCollection addItemsItem(AssetWrapper itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * List of assets
   * @return items
  **/
  @ApiModelProperty(example = "null", value = "List of assets")
  public List<AssetWrapper> getItems() {
    return items;
  }

  public void setItems(List<AssetWrapper> items) {
    this.items = items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetCollection assetCollection = (AssetCollection) o;
    return Objects.equals(this.href, assetCollection.href) &&
        Objects.equals(this.items, assetCollection.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetCollection {\n");
    
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

