/*
 * Apache Ambari - Management Pack Store Provider APIs
 * Management pack store provider APIs for Apache Ambari  [Learn about Apache Ambari](https://ambari.apache.org/) 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ambari.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PackageVersionWrapper;
import java.util.ArrayList;
import java.util.List;

/**
 * PackageVersionCollection
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T19:27:10.581Z")
public class PackageVersionCollection {
  @SerializedName("href")
  private String href = null;

  @SerializedName("items")
  private List<PackageVersionWrapper> items = new ArrayList<PackageVersionWrapper>();

  public PackageVersionCollection href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public PackageVersionCollection items(List<PackageVersionWrapper> items) {
    this.items = items;
    return this;
  }

  public PackageVersionCollection addItemsItem(PackageVersionWrapper itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * List of package versions
   * @return items
  **/
  @ApiModelProperty(example = "null", value = "List of package versions")
  public List<PackageVersionWrapper> getItems() {
    return items;
  }

  public void setItems(List<PackageVersionWrapper> items) {
    this.items = items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageVersionCollection packageVersionCollection = (PackageVersionCollection) o;
    return Objects.equals(this.href, packageVersionCollection.href) &&
        Objects.equals(this.items, packageVersionCollection.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageVersionCollection {\n");
    
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

